apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-nginx-certificate
  namespace: nginx
spec:
  secretName: my-nginx-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - www.icetechnology.com.ve
