apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-certificate
  namespace: wordpress
spec:
  secretName: wordpress-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - www.icetechnology.com.ve