apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laravel-demo-certificate
  namespace: laravel-demo
spec:
  secretName: laravel-demo-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - crm.icetechnology.com.ve