apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-uptime-kuma-certificate
  namespace: uptime-kuma
spec:
  secretName: my-uptime-kuma-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - kuma.icetechnology.com.ve
